Update variable, add blank line

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -21,18 +21,6 @@ jobs:
         - |
           ./scripts/get-updated-distros.sh |
             while read -r filename; do
-<<<<<<< HEAD
-              if [ "$filename" == "_topic_maps/_topic_map.yml" ]; then python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.14 --no-upstream-fetch || travis_terminate 1
-
-              elif [ "$filename" == "_topic_maps/_topic_map_osd.yml" ]; then python3 build.py --distro openshift-dedicated --product "OpenShift Dedicated" --version 4 --no-upstream-fetch || travis_terminate 1
-
-              elif [ "$filename" == "_topic_maps/_topic_map_ms.yml" ]; then python3 build.py --distro microshift --product "Microshift" --version 4 --no-upstream-fetch || travis_terminate 1
-
-              elif [ "$filename" == "_topic_maps/_topic_map_rosa.yml" ]; then python3 build.py --distro openshift-rosa --product "Red Hat OpenShift Service on AWS" --version 4 --no-upstream-fetch || travis_terminate 1
-
-              elif [ "$filename" == "_distro_map.yml" ]; then python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.14 --no-upstream-fetch || travis_terminate 1
-              fi
-=======
               case "$filename" in
                 "_topic_maps/_topic_map.yml")
                   distro="openshift-enterprise"
@@ -60,12 +48,11 @@ jobs:
                   version="4.14"
                   ;;
                 *)
-                  echo "Error: Unrecognized filename: $FILENAME" >&2
+                  echo "Error: Unrecognized filename: $filename" >&2
                   exit 1
                   ;;
               esac
               python3 build_for_portal.py --distro "$distro" --product "$product" --version "$version" --no-upstream-fetch
               if [ $? -ne 0 ]; then travis_terminate 1; fi
->>>>>>> 6707a18286 (Fail check)
             done
         - if [ -d "drupal-build" ]; then python3 makeBuild.py || travis_terminate 1; fi
