Fail check

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,7 +6,7 @@ git:
   depth: 10
 jobs:
   include:
-      name: "Preview, validate, and build"
+    - name: "Preview, validate, and build"
       before_install:
         - chmod +x autopreview.sh
         - ./autopreview.sh
@@ -21,6 +21,7 @@ jobs:
         - |
           ./scripts/get-updated-distros.sh |
             while read -r filename; do
+<<<<<<< HEAD
               if [ "$filename" == "_topic_maps/_topic_map.yml" ]; then python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.14 --no-upstream-fetch || travis_terminate 1
 
               elif [ "$filename" == "_topic_maps/_topic_map_osd.yml" ]; then python3 build.py --distro openshift-dedicated --product "OpenShift Dedicated" --version 4 --no-upstream-fetch || travis_terminate 1
@@ -31,6 +32,40 @@ jobs:
 
               elif [ "$filename" == "_distro_map.yml" ]; then python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.14 --no-upstream-fetch || travis_terminate 1
               fi
+=======
+              case "$filename" in
+                "_topic_maps/_topic_map.yml")
+                  distro="openshift-enterprise"
+                  product="OpenShift Container Platform"
+                  version="4.14"
+                  ;;
+                "_topic_maps/_topic_map_osd.yml")
+                  distro="openshift-dedicated"
+                  product="OpenShift Dedicated"
+                  version="4"
+                  ;;
+                "_topic_maps/_topic_map_ms.yml")
+                  distro="microshift"
+                  product="Microshift"
+                  version="4"
+                  ;;
+                "_topic_maps/_topic_map_rosa.yml")
+                  distro="openshift-rosa"
+                  product="Red Hat OpenShift Service on AWS"
+                  version="4"
+                  ;;
+                "_distro_map.yml")
+                  distro="openshift-enterprise"
+                  product="OpenShift Container Platform"
+                  version="4.14"
+                  ;;
+                *)
+                  echo "Error: Unrecognized filename: $FILENAME" >&2
+                  exit 1
+                  ;;
+              esac
+              python3 build.py --distro "$distro" --product "$product" --version "$version" --no-upstream-fetch
+              if [ $? -ne 0 ]; then travis_terminate 1; fi
+>>>>>>> 6707a18286 (Fail check)
             done
-
-          if [ -d "drupal-build" ]; then python3 makeBuild.py; fi
+        - if [ -d "drupal-build" ]; then python3 makeBuild.py || travis_terminate 1; fi
