Sync Travis updates from main

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,45 +1,43 @@
 language: python
 cache:
   pip: true
-  directories:
-    - /home/travis/.rvm/gems
+
 git:
-  depth: 2
+  depth: 10
 jobs:
-  allow_failures:
-    env:
-      - CAN_FAIL=true
-
   include:
-    - stage: cache-and-validate
-      name: "Create install cache and validate updated assemblies"
-      install:
-        - gem install asciidoctor asciidoctor-diagram rouge
-        - pip3 install pyyaml aura.tar.gz
-      script:
-        # Fail if Asciidoctor encounters errors. Run only if there are modified AsciiDoc files
-        - chmod +x ./scripts/check-asciidoctor-build.sh
-        - ./scripts/check-asciidoctor-build.sh || travis_terminate 1
-
-    - stage: build
-      name: "Build openshift-acs distro"
-      install:
-        - gem install asciidoctor asciidoctor-diagram rouge
-        - pip3 install pyyaml aura.tar.gz
-      script:
-        - python3 build.py --distro openshift-acs --product "Red Hat Advanced Cluster Security for Kubernetes" --version 4.1 --no-upstream-fetch && python3 makeBuild.py
-
-    - stage: netlify
-      name: "Create Netlify preiview"
-      env:
-        - CAN_FAIL=true
-      language: minimal
-      if: type IN (pull_request) AND branch IN (rhacs-docs, rhacs-docs-3.74, rhacs-docs-4.0, rhacs-docs-4.1, rhacs-docs-4.2)
-      script:
+    - name: "Preview, validate, and build"
+      before_install:
         - chmod +x autopreview.sh
         - ./autopreview.sh
-
-stages:
-  - cache-and-validate
-  - build
-  - netlify
+      install:
+        - gem install --local _gemfiles/asciidoctor-2.0.20.gem _gemfiles/asciidoctor-diagram-plantuml-1.2023.10.gem _gemfiles/asciidoctor-diagram-ditaamini-1.0.3.gem _gemfiles/rexml-3.2.6.gem _gemfiles/asciidoctor-diagram-2.2.14.gem _gemfiles/rouge-4.1.3.gem
+        - pip3 install pyyaml aura.tar.gz
+      script:
+        # Fail if Asciidoctor encounters errors. Pass otherwise. Then, build updated distros
+        - chmod +x ./scripts/check-asciidoctor-build.sh
+        - chmod +x ./scripts/get-updated-distros.sh
+        - ./scripts/check-asciidoctor-build.sh || travis_terminate 1
+        - |
+          ./scripts/get-updated-distros.sh |
+            while read -r filename; do
+              case "$filename" in
+                "_topic_map.yml")
+                  distro="openshift-acs"
+                  product="Red Hat Advanced Cluster Security for Kubernetes"
+                  version="4.3"
+                  ;;
+                "_distro_map.yml")
+                  distro="openshift-acs"
+                  product="Red Hat Advanced Cluster Security for Kubernetes"
+                  version="4.3"
+                  ;;
+                *)
+                  echo "Output from get-updated-distros.sh: $filename"
+                  echo -e "\033[1;33m No topic maps or distro_map modified!\033[0m"
+                  ;;
+              esac
+              python3 build.py --distro "$distro" --product "$product" --version "$version" --no-upstream-fetch
+              if [ $? -ne 0 ]; then travis_terminate 1; fi
+            done
+        - if [ -d "drupal-build" ]; then python3 makeBuild.py || travis_terminate 1; fi
