This change should fail the build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -21,15 +21,38 @@ jobs:
         - |
           ./scripts/get-updated-distros.sh |
             while read -r filename; do
-              if [ "$filename" == "_topic_maps/_topic_map.yml" ]; then python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.14 --no-upstream-fetch
-
-              elif [ "$filename" == "_topic_maps/_topic_map_osd.yml" ]; then python3 build.py --distro openshift-dedicated --product "OpenShift Dedicated" --version 4 --no-upstream-fetch
-
-              elif [ "$filename" == "_topic_maps/_topic_map_ms.yml" ]; then python3 build.py --distro microshift --product "Microshift" --version 4 --no-upstream-fetch
-
-              elif [ "$filename" == "_topic_maps/_topic_map_rosa.yml" ]; then python3 build.py --distro openshift-rosa --product "Red Hat OpenShift Service on AWS" --version 4 --no-upstream-fetch
-
-              elif [ "$filename" == "_distro_map.yml" ]; then python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.14 --no-upstream-fetch
-              fi
+              case "$filename" in
+                "_topic_maps/_topic_map.yml")
+                  distro="openshift-enterprise"
+                  product="OpenShift Container Platform"
+                  version="4.14"
+                  ;;
+                "_topic_maps/_topic_map_osd.yml")
+                  distro="openshift-dedicated"
+                  product="OpenShift Dedicated"
+                  version="4"
+                  ;;
+                "_topic_maps/_topic_map_ms.yml")
+                  distro="microshift"
+                  product="Microshift"
+                  version="4"
+                  ;;
+                "_topic_maps/_topic_map_rosa.yml")
+                  distro="openshift-rosa"
+                  product="Red Hat OpenShift Service on AWS"
+                  version="4"
+                  ;;
+                "_distro_map.yml")
+                  distro="openshift-enterprise"
+                  product="OpenShift Container Platform"
+                  version="4.14"
+                  ;;
+                *)
+                  echo "Error: Unrecognized filename: $FILENAME" >&2
+                  exit 1
+                  ;;
+              esac
+              python3 build.py --distro "$distro" --product "$product" --version "$version" --no-upstream-fetch
+              if [ $? -ne 0 ]; then travis_terminate 1; fi
             done
         - if [ -d "drupal-build" ]; then python3 makeBuild.py || travis_terminate 1; fi
